dist: trusty
sudo: required

stages:
- name: install
  if: branch = travis
jobs:
  include:
  - stage: install
    before_install:
      - sudo service mysql stop
      - sudo service elasticsearch stop
    script:
      - ./tests/setup.sh
      - ./tests/stop.sh
