dist: trusty
sudo: required

stages:
- name: web_tests
jobs:
  include:
  - stage: web_tests
    before_install:
      - sudo service mysql stop
      - sudo service elasticsearch stop
      - cp -r tests/web_tests/* ./data/app/sugar/
    script:
      - ./tests/web_tests.sh
