dist: trusty
sudo: required

stages:
- name: start
- name: web_tests
- name: stop
jobs:
  include:
  - stage: start
    before_install:
      - sudo service mysql stop
      - sudo service elasticsearch stop
    script:
      - ./tests/start.sh
  - stage: web_tests
    before_install:
      - cp -r tests/web_tests/* ./data/app/sugar/
    script:
      - ./tests/web_tests.sh
  - stage: stop
    script:
      - ./tests/stop.sh
