dist: trusty
sudo: true

services:
  - docker

env:
  - STACK=stacks/sugar81/php71.yml SUGAR=8.1 PHP=7.1

before_install:
  - sudo service mysql stop
  - sudo service elasticsearch stop
install:
  - echo "docker.local 127.0.0.1" | sudo tee -a /etc/hosts > /dev/null
  - mkdir ./data/app/sugar/web_tests
  - cp -r ./tests/web_tests/$PHP/* ./data/app/sugar/web_tests/
before_script:
  - sudo sysctl -w vm.max_map_count=262144
script:
  - ./tests/start.sh $STACK
  - ./tests/web_tests.sh
  - ./tests/stop.sh $STACK
