dist: trusty
sudo: required

stages:
- name: start
- name: stop
jobs:
  include:
  - stage: start
    before_install:
      - sudo service mysqld stop
      - sudo service elasticsearch stop
    script:
      - ./tests/start.sh
  - stage: stop
    script:
      - ./test/stop.sh
